/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreatorSourcingRouteImport } from './routes/creator-sourcing'
import { Route as IndexRouteImport } from './routes/index'

const CreatorSourcingRoute = CreatorSourcingRouteImport.update({
  id: '/creator-sourcing',
  path: '/creator-sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creator-sourcing': typeof CreatorSourcingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creator-sourcing': typeof CreatorSourcingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creator-sourcing': typeof CreatorSourcingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/creator-sourcing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/creator-sourcing'
  id: '__root__' | '/' | '/creator-sourcing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatorSourcingRoute: typeof CreatorSourcingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/creator-sourcing': {
      id: '/creator-sourcing'
      path: '/creator-sourcing'
      fullPath: '/creator-sourcing'
      preLoaderRoute: typeof CreatorSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorSourcingRoute: CreatorSourcingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
